function getApiKey() {
  const storedKey = localStorage.getItem("gemini_api_key");
  if (storedKey && storedKey.trim() !== "" && !storedKey.includes("DUMMY_KEY")) {
    return storedKey.trim();
  }
  return import.meta.env.VITE_GEMINI_API_KEY || "YOUR_GEMINI_API_KEY";
}

async function askGemini(promptText) {
  const apiKey = getApiKey();
  const apiURL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;

  try {
    const response = await fetch(apiURL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: promptText
              }
            ]
          }
        ]
      })
    });

    if (!response.ok) {
      throw new Error(`Gemini API error: ${response.status} ${response.statusText}`);
    }

    const data = await response.json();
    if (data.candidates && data.candidates[0] && data.candidates[0].content && data.candidates[0].content.parts[0]) {
      return data.candidates[0].content.parts[0].text.trim();
    }
    return "No suggestions generated by AI.";
  } catch (error) {
    console.error("Error communicating with Gemini AI:", error);
    return `AI assistant unavailable: ${error.message}`;
  }
}

// Helper to clean HTML tags and trim
function getPlainText(html) {
  if (!html) return "";
  return html.replace(/<[^>]*>/g, "").replace(/&nbsp;/g, " ").trim();
}

// Helper for random selection
function getRandomElement(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

// 1. Headline / Title Generator
export async function generateHeadlineSuggestions(content, category = "Essay") {
  const plainText = getPlainText(content);
  if (!plainText) return ["Draft is empty. Type some content first."];
  
  try {
    const prompt = `Based on the following article content, generate 3 unique, catchy, and professional headlines or titles. Return ONLY the titles in a numbered list (e.g., "1. Title One\\n2. Title Two\\n3. Title Three") without any conversational introduction or explanation.\n\nContent:\n${plainText.substring(0, 3000)}`;
    const result = await askGemini(prompt);
    if (!result || result.includes("AI assistant unavailable") || result.includes("Gemini API error")) {
      throw new Error("Gemini API limit or error");
    }
    return result
      .split("\n")
      .map(line => line.replace(/^\d+\.\s*/, "").trim())
      .filter(line => line.length > 0);
  } catch (error) {
    console.warn("Using local fallback for Title Suggestions:", error);
    const words = plainText.split(/\s+/).slice(0, 4).join(" ");
    const cat = (category || "Essay").toLowerCase();
    
    if (cat.includes("poetry")) {
      return [
        `Whispers of the Soul: ${words}...`,
        `The Echoing Verse`,
        `Starlight and Silences`
      ];
    } else if (cat.includes("fiction")) {
      return [
        `The Mystery of "${words}..."`,
        `A Twist of Fate`,
        `Beyond the Threshold`
      ];
    } else if (cat.includes("journal")) {
      return [
        `Daily Reflections: ${words}...`,
        `Moments of Clarity`,
        `The Inner Canvas`
      ];
    } else {
      return [
        `Reflections on "${words}..."`,
        `The Silent Chronicle: A Study in Expression`,
        `Exploring the Depths of Personal Narrative`
      ];
    }
  }
}

// 2. AI Writing Assistant (Continue/Improve Writing)
export async function improveWritingStyle(content, category = "Essay") {
  const plainText = getPlainText(content);
  if (!plainText) return "Your canvas is empty. Start typing, then ask me to expand or refine it!";
  
  try {
    const prompt = `Analyze the following text and continue writing it, adding another well-written paragraph. Maintain the tone, style, and vocabulary of the author. Return ONLY the added continuation text. Do not add comments, descriptions, or quotes.\n\nText:\n${plainText.substring(0, 3000)}`;
    const result = await askGemini(prompt);
    if (!result || result.includes("AI assistant unavailable") || result.includes("Gemini API error")) {
      throw new Error("Gemini API limit or error");
    }
    return result;
  } catch (error) {
    console.warn("Using local fallback for Auto-Write:", error);
    const cat = (category || "Essay").toLowerCase();
    
    const poetryOptions = [
      "Beneath the silent stars and whispers of the wind, thoughts echo into the canvas of the mind. Each word is a footprint in the sand, washed away by the tide, yet forever etched in the memory of the shore.",
      "Shadows dance across the ancient page, tracing the contours of a forgotten dream. In the quiet space between heartbeats, a single voice rises, singing of time's slow and patient unraveling.",
      "The ink runs deep like rivers in the spring, carrying the weight of unuttered songs. We write not to be remembered, but to capture the transient spark of a moment fading into twilight."
    ];
    
    const fictionOptions = [
      "Suddenly, a shadow flickered across the wall, and the silence of the room was broken by a soft, rhythmic tapping on the windowpane. It was a sound he hadn't heard in years, a reminder of things left unfinished.",
      "She hesitated at the threshold, the cold draft from the hallway brushing against her face. The old house seemed to breathe around her, its timbers creaking with secrets that had slept undisturbed for decades.",
      "The engine roared to life with a metallic cough, casting long beams of amber light through the dense morning fog. He didn't look back; the map on the passenger seat was the only guide he needed now."
    ];
    
    const journalOptions = [
      "Reflecting on these events, it becomes clear that self-discovery is a gradual journey, marked by small moments of realization rather than grand epiphanies. The path forward remains unclear, but the first step has been taken.",
      "Today was one of those quiet days where nothing of note happened, yet everything felt subtly shifted. I spent the afternoon thinking about how quickly priorities change and what it truly means to be present.",
      "It is easy to get caught up in the noise of daily routines, but writing these thoughts down always helps clear the dust. I am learning to appreciate the pauses between major milestones."
    ];
    
    const essayOptions = [
      "Furthermore, when analyzing this topic, it is crucial to consider the broader context and the implications of these concepts on our understanding. Every step forward in our narrative represents a transition between what was observed and what is yet to be discovered, reminding us of the paths left unexplored.",
      "In addition, a closer examination of the underlying evidence suggests that these patterns are not isolated occurrences, but rather systemic trends that require careful critical assessment. This perspective challenges conventional interpretations and invites a more nuanced approach.",
      "Consequently, the debate surrounding these findings remains highly relevant in contemporary discussions. As we synthesize these opposing viewpoints, it becomes clear that a collaborative framework is essential to address the unresolved questions in this domain."
    ];

    if (cat.includes("poetry")) {
      return getRandomElement(poetryOptions);
    } else if (cat.includes("fiction")) {
      return getRandomElement(fictionOptions);
    } else if (cat.includes("journal")) {
      return getRandomElement(journalOptions);
    } else {
      return getRandomElement(essayOptions);
    }
  }
}

// 3. Grammar and Style suggestions
export async function checkGrammarAndStyle(content) {
  const plainText = getPlainText(content);
  if (!plainText) return "Write some text first to run a grammar scan.";
  
  try {
    const prompt = `Review the following text for spelling, grammar errors, and style issues. If there are errors, return a concise bulleted list explaining what to fix and how. If the text is perfect, write "Everything looks excellent! No corrections needed."\n\nText:\n${plainText.substring(0, 3000)}`;
    const result = await askGemini(prompt);
    if (!result || result.includes("AI assistant unavailable") || result.includes("Gemini API error")) {
      throw new Error("Gemini API limit or error");
    }
    return result;
  } catch (error) {
    console.warn("Using local fallback for Grammar check:", error);
    const errors = [];
    if (plainText.includes("  ")) {
      errors.push("• Style: Found double spacing between words. Consider formatting to single spacing.");
    }
    // Check if sentences start with capital letters
    const sentences = plainText.split(/[.!?]\s+/);
    let capitalizedError = false;
    for (let s of sentences) {
      if (s && s[0] !== s[0].toUpperCase()) {
        capitalizedError = true;
        break;
      }
    }
    if (capitalizedError) {
      errors.push("• Grammar: Ensure all sentences start with a capital letter.");
    }
    
    // Spellcheck common words
    const commonMisspells = {
      "teh": "the",
      "recieve": "receive",
      "dont": "don't",
      "im": "I'm",
      "wont": "won't",
      "aboutt": "about"
    };
    const words = plainText.toLowerCase().split(/\s+/);
    for (let w of words) {
      const cleanW = w.replace(/[^a-z]/g, "");
      if (commonMisspells[cleanW]) {
        errors.push(`• Spelling: Potential typo "${cleanW}". Did you mean "${commonMisspells[cleanW]}"?`);
      }
    }
    
    if (errors.length === 0) {
      return "Everything looks excellent! Local scan found no formatting or capitalization issues. (Offline fallback active)";
    }
    return "Grammar & Style Scan Results (Local Fallback):\n" + errors.join("\n");
  }
}

// 4. Article Summarization
export async function summarizeArticleText(content) {
  const plainText = getPlainText(content);
  if (!plainText) return "No text available to summarize.";
  
  try {
    const prompt = `Summarize the following text in exactly one or two powerful sentences, suitable as a reading preview. Return ONLY the summary sentences, nothing else.\n\nText:\n${plainText.substring(0, 3000)}`;
    const result = await askGemini(prompt);
    if (!result || result.includes("AI assistant unavailable") || result.includes("Gemini API error")) {
      throw new Error("Gemini API limit or error");
    }
    return result;
  } catch (error) {
    console.warn("Using local fallback for Summary:", error);
    const sentences = plainText.split(/[.!?]/).filter(s => s.trim().length > 5);
    const summaryBase = sentences[0] ? sentences[0].trim() : plainText.substring(0, 100);
    return `${summaryBase}. (A reflective exploration on thoughts, structure, and community narratives.)`;
  }
}

// 5. Generate Keywords for Cover Photo
export async function generateCoverKeywords(title, content) {
  const plainText = getPlainText(content);
  const context = `Title: ${title}\nContent Preview: ${plainText ? plainText.substring(0, 500) : ""}`;
  const prompt = `Given the following article details, output exactly 2 simple keywords (comma-separated, e.g. "writing, desk" or "nature, forest") that represent a matching background scene for this article. Output ONLY the two words, no punctuation or explanation.\n\n${context}`;
  
  try {
    const keywords = await askGemini(prompt);
    if (!keywords || keywords.includes("AI assistant unavailable") || keywords.includes("Gemini API error")) {
      throw new Error("Gemini API limit or error");
    }
    return keywords.replace(/[^a-zA-Z0-9,\s]/g, "").trim() || "writing,book";
  } catch (error) {
    console.warn("Using local fallback for cover keywords:", error);
    const titleWords = (title || "")
      .toLowerCase()
      .replace(/[^a-z\s]/g, "")
      .split(/\s+/)
      .filter(w => w.length > 3 && !["with", "from", "that", "this", "your", "their", "about", "here", "there"].includes(w));
    return titleWords.slice(0, 2).join(",") || "writing";
  }
}
