spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://admin:admin@cluster0.gyurphn.mongodb.net/semendproject?appName=Cluster0}

server.port=${PORT:8080}

# Gemini API Integration
gemini.api.key=${GEMINI_API_KEY:YOUR_GEMINI_API_KEY}